version: "3"
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile

    ports:
      - "5000:5000"
    volumes:
      - ../app/:/home/app/
    env_file: .env
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
